// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvqbghtrvlnqygyoherj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2cWJnaHRydmxucXlneW9oZXJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NDA4ODAsImV4cCI6MjA2NTExNjg4MH0.M1jVsIBs63KrIMirYTPU6oxV07SoDrcwdU-uSibnpJs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);